= TypeDB Cloud API Reference
:page-toclevels: 2

== Authorization

=== Token Exchange

Exchange an API token's client ID and client secret for a short-lived access token to authenticate against the rest of the API.

[cols="h,3a"]
|===
| Required access          | None
| Method                   | `POST`
| URL                      | `/api/auth`
| Request body             | None
| Request headers          | `Authorization: Basic CLIENT_ID:CLIENT_SECRET`
|===

*Responses:*

.200: OK
[%collapsible]
====
This response will contain only the access token

Response format:

[source]
----
string
----
====

.400: Bad Request
[%collapsible]
====
Possible causes:

* Incorrectly formatted request (e.g. Authorization header missing a token)
* Invalid client ID
* Invalid client secret

Response format:

include::{page-version}@manual:resources:partial$cloud-api/error-response.json.adoc[]
====

*Example request:*
[tabs]
====
curl::
+
[source,console]
----
curl --request POST \
    --url https://cloud.typedb.com/api/auth \
    --header 'Authorization: Basic {CLIENT_ID}:{CLIENT_SECRET}'
----

Python::
+
[source,python]
----
import requests

url = "https://cloud.typedb.com/api/auth"

headers = {
    "Authorization": "Basic {CLIENT_ID}:{CLIENT_SECRET}"
}

response = requests.post(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .post("https://cloud.typedb.com/api/auth")
        .header(reqwest::header::AUTHORIZATION, "Basic {CLIENT_ID}:{CLIENT_SECRET}")
        .send().await;
    Ok(())
}
----
====

*Example response:*
[source]
----
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
----

[#accesslevels]
=== API Token Access Levels

When generating your API token, you will grant it a certain access level to a space of your choice.
It will be able to perform the actions within that space as described below:

[options="header"]
|===
| Project access level | Available cluster actions
| Admin                | Destroy
| Write                | Deploy, Suspend, Resume
| Read                 | Get, List
|===

== Clusters

=== Deploy

[cols="h,3a"]
|===
| Required access          | *write* to `team/TEAM_ID/spaces/SPACE_ID`
| Method                   | `POST`
| URL                      | `/api/team/TEAM_ID/spaces/SPACE_ID/clusters/deploy`
| Request body             | include::{page-version}@manual:resources:partial$cloud-api/cluster-deploy.json.adoc[]
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@manual:resources:partial$cloud-api/response-details.adoc[tags="200-single,400,401,403,404,409,500"]

[NOTE]
====
Clusters deployed through the API will have a default user with the username `admin` and the password `password`.
We recommend xref:{page-version}@manual::users/passwords.adoc[updating the default password] before using the cluster -
which can also be done through the TypeDB Cloud UI by clicking the "Connect" button on the cluster's page.
====

*Example request:*

[tabs]
====
curl::
+
[source,console]
----
curl --request POST \
    --url https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/deploy \
    --header 'Authorization: Bearer {ACCESS-TOKEN}' \
    --json '{"id":"api-cluster","serverCount":1,"storageSizeGB":10,"provider":"gcp","region":"europe-west2","isFree":true,"machineType":"c2d-highcpu-2","storageType":"standard-rwo","version":"3.1.0"}'
----

Python::
+
[source,python]
----
import requests

url = "https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/deploy[https://cloud.typedb.com/api/auth]"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

body = {
    "id": "api-cluster",
    "serverCount": 1,
    "storageSizeGB": 10,
    "provider": "gcp",
    "region": "europe-west2",
    "isFree": True,
    "machineType": "c2d-highcpu-2",
    "storageType": "standard-rwo",
    "version": "3.1.0"
}

response = requests.post(url, headers=headers, json=body)
----

Rust::
+
[source,rust]
----
use reqwest;
use serde::Serialize;

#[derive(Serialize)]
struct ClusterDeploy {
    id: String,
    serverCount: i32,
    storageSizeGB: i32,
    provider: String,
    region: String,
    isFree: bool,
    machineType: String,
    storageType: String,
    version: String
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cluster_deploy = ClusterDeploy {
        id: "api-cluster".into(),
        serverCount: 1,
        storageSizeGB: 10,
        provider: "gcp".into(),
        region: "europe-west2".into(),
        isFree: true,
        machineType: "c2d-highcpu-2".into(),
        storageType: "standard-rwo".into(),
        version: "3.1.0".into()
    };
    let client = reqwest::Client::new();
    let resp = client
        .post("https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/deploy")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .json(&cluster_deploy)
        .send().await;
    Ok(())
}
----

Request Body::
+
[source,json]
----
{
    "id":"api-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "provider":"gcp",
    "region":"europe-west2",
    "isFree":true,
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "version":"3.1.0"
}
----
====

*Example response:*
[source,json]
----
{
    "id":"api-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "isFree":true,
    "status":"starting",
    "createdAt":1738256490070,
    "teamID":"new-team",
    "spaceID":"default",
    "version":"3.1.0",
    "provider":"gcp",
    "region":"europe-west2",
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "servers": [
        {
          "address": "abc123-0.cluster.typedb.com:80",
          "status": "pending"
        }
    ]
}
----

[options="header"]
|===
| Field | Allowed Values
| `id` | The cluster's ID must be unique within its space,
and consist only of lowercase alphanumeric characters, optionally separated by underscores and hyphens.
| `serverCount` | An odd integer value between 1 and 9.
TypeDB version 3.0 and onwards can currently only have one server.
| `storageSizeGB` | An integer value between 10 and 1000.
| `provider` | Must be either `gcp` or `aws`
| `isFree` | If set to `true`, must use a valid free machine type, and have at most 1 server and 10GB of storage.
You may only have one free cluster per team.

If set to `false`, there must be a valid payment method on the team.
| `region` | See <<regionsmachinetypes,below>>
| `machineType` | See <<regionsmachinetypes,below>>
| `storageType` | See <<storagetypes,below>>
| `version` a| Currently available versions are:

* `2.29.3`
* `3.0.6`
* `3.1.0`
|===

[#regionsmachinetypes]
.GCP regions and machine types
[%collapsible]
====
[options="header",cols=",,a"]
|===
| Machine Types    | Free Available | Regions
| c2d-highcpu-2    | Yes            |
* europe-west2
* europe-west3
* us-west4
* us-east1
| c2d-highcpu-4    | No             |
* europe-west2
* europe-west3
* us-west4
* us-east1
| c2d-highcpu-8    | No             |
* europe-west2
* europe-west3
* us-west4
* us-east1
| c2d-highcpu-16   | No             |
* europe-west2
* europe-west3
* us-west4
* us-east1
|===
====

.AWS regions and machine types
[%collapsible]
====
[options="header",cols=",,a"]
|===
| Machine Types    | Free Available | Regions
| c7g.large        | Yes            |
* eu-west-2
| c7g.xlarge       | No             |
* eu-west-2
| c7g.2xlarge      | No             |
* eu-west-2
| c7g.4xlarge      | No             |
* eu-west-2
| c8g.large        | Yes            |
* us-west-2
* us-east-1
* eu-central-1
| c8g.xlarge       | No             |
* us-west-2
* us-east-1
* eu-central-1
| c8g.2xlarge      | No             |
* us-west-2
* us-east-1
* eu-central-1
| c8g.4xlarge      | No             |
* us-west-2
* us-east-1
* eu-central-1
|===
====

.Storage types
[#storagetypes]
[%collapsible]
====
[options="header"]
|===
| Provider | Storage Type
| GCP      | standard-rwo
| AWS      | gp2
|===
====

=== Get

[cols="h,3a"]
|===
| Required access          | *read* to `team/TEAM_ID/spaces/SPACE_ID`
| Method                   | `GET`
| URL                      | `/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@manual:resources:partial$cloud-api/response-details.adoc[tags="200-single,400,401,403,404,500"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----
curl --request GET \
    --url https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID \
    --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.get(url, headers=headers)
----

Rust::
+
[source,rust]
----
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .get("https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

*Example response:*
[source,json]
----
{
    "id":"new-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "isFree":true,
    "status":"running",
    "createdAt":1738256490070,
    "teamID":"new-team",
    "spaceID":"default",
    "version":"3.1.0",
    "provider":"gcp",
    "region":"europe-west2",
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "servers": [
        {
          "address": "abc123-0.cluster.typedb.com:80",
          "status": "running"
        }
    ]
}
----

=== List

[cols="h,3a"]
|===
| Required access          | *read* to `team/TEAM_ID/spaces/SPACE_ID`
| Method                   | `GET`
| URL                      | `/api/team/TEAM_ID/spaces/SPACE_ID/clusters`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@manual:resources:partial$cloud-api/response-details.adoc[tags="200-list,400,401,403,404,500"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----
curl --request GET \
    --url https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters \
    --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.get(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .get("https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

*Example response:*
[source,json]
----
[
    {
        "id":"new-cluster",
        "serverCount":1,
        "storageSizeGB":10,
        "isFree":true,
        "status":"running",
        "createdAt":1738256490070,
        "teamID":"new-team",
        "spaceID":"default",
        "version":"3.1.0",
        "provider":"gcp",
        "region":"europe-west2",
        "machineType":"c2d-highcpu-2",
        "storageType":"standard-rwo",
        "servers": [
            {
              "address": "abc123-0.cluster.typedb.com:80",
              "status": "running"
            }
        ]
    },
    {
        "id":"cluster-two",
        "serverCount":1,
        "storageSizeGB":10,
        "isFree":false,
        "status":"suspended",
        "createdAt":1738256490090,
        "teamID":"new-team",
        "spaceID":"default",
        "version":"3.1.0",
        "provider":"aws",
        "region":"eu-west-2",
        "machineType":"c7g.large",
        "storageType":"gp2",
        "servers": []
    }
]
----


=== Suspend

[cols="h,3a"]
|===
| Required access          | *write* to `team/TEAM_ID/spaces/SPACE_ID`
| Method                   | `POST`
| URL                      | `/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID/suspend`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@manual:resources:partial$cloud-api/response-details.adoc[tags="200-single,400,401,403,404,500"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----
curl --request POST \
    --url https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID/suspend \
    --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID/suspend"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.post(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .post("https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID/suspend")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

*Example response:*
[source,json]
----
{
    "id":"new-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "isFree":true,
    "status":"suspending",
    "createdAt":1738256490070,
    "teamID":"new-team",
    "spaceID":"default",
    "version":"3.1.0",
    "provider":"gcp",
    "region":"europe-west2",
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "servers": [
        {
          "address": "abc123-0.cluster.typedb.com:80",
          "status": "running"
        }
    ]
}
----

=== Resume

[cols="h,3a"]
|===
| Required access          | *write* to `team/TEAM_ID/spaces/SPACE_ID`
| Method                   | `POST`
| URL                      | `/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID/resume`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@manual:resources:partial$cloud-api/response-details.adoc[tags="200-single,400,401,403,404,500"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----
curl --request POST \
    --url https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID/resume \
    --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID/resume"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.post(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .post("https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID/resume")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

*Example response:*
[source,json]
----
{
    "id":"new-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "isFree":true,
    "status":"resuming",
    "createdAt":1738256490070,
    "teamID":"new-team",
    "spaceID":"default",
    "version":"3.1.0",
    "provider":"gcp",
    "region":"europe-west2",
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "servers": [
        {
          "address": "abc123-0.cluster.typedb.com:80",
          "status": "pending"
        }
    ]
}
----

=== Destroy

[cols="h,3a"]
|===
| Required access          | *admin* to `team/TEAM_ID/spaces/SPACE_ID`
| Method                   | `DELETE`
| URL                      | `/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@manual:resources:partial$cloud-api/response-details.adoc[tags="200-single,400,401,403,404,500"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----
curl --request DELETE \
    --url https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID \
    --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.delete(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .delete("https://cloud.typedb.com/api/team/TEAM_ID/spaces/SPACE_ID/clusters/CLUSTER_ID")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

*Example response:*
[source,json]
----
{
    "id":"new-cluster",
    "serverCount":1,
    "storageSizeGB":10,
    "isFree":true,
    "status":"destroying",
    "createdAt":1738256490070,
    "teamID":"new-team",
    "spaceID":"default",
    "version":"3.1.0",
    "provider":"gcp",
    "region":"europe-west2",
    "machineType":"c2d-highcpu-2",
    "storageType":"standard-rwo",
    "servers": [
        {
          "address": "abc123-0.cluster.typedb.com:80",
          "status": "running"
        }
    ]
}
----
