// tag::install-apt[]

. Add the TypeDB repository:
+
[source,bash]
----
sudo apt install software-properties-common apt-transport-https gpg
gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key 17507562824cfdcc
gpg --export 17507562824cfdcc | sudo tee /etc/apt/trusted.gpg.d/typedb.gpg > /dev/null
echo "deb https://repo.typedb.com/public/public-release/deb/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/typedb.list > /dev/null
sudo apt update
----
. Install TypeDB:
+
[source,bash]
----
sudo apt install typedb
----
+
If you had an older version of TypeDB installed, you might first need to uninstall older packages to avoid
conflicts:
+
[source,bash]
----
sudo apt remove typedb-server typedb-bin typedb-console
----
////
The `typedb-server` and `typedb-console` packages are updated more often than `typedb-bin`, so their
version numbers might differ. By default, APT will look for the exact same version of `typedb-bin`,
resulting in an error. To prevent this, use `apt show`, as shown above, to find a compatible version first, and then
invoke an `apt install` command with the specific version for every package.
////
// end::install-apt[]

// tag::manual-install[]
. Extract the archive with TypeDB into a new directory:
+
[source,bash]
----
mkdir /opt/typedb
tar -xzf ~/Downloads/<filename>.tar.gz -C /opt/typedb
----
+
Where `<filename>` is the name of the archive.
. Add a symlink to the TypeDB executable in the `/usr/local/bin` directory:
+
[source,bash]
----
ln -s /opt/typedb/<filename>/typedb /usr/local/bin/typedb
----

// end::manual-install[]

// tag::start[]
To run TypeDB Community Edition installed locally:

[source,bash]
----
typedb server
----
// end::start[]

// tag::stop[]

To stop TypeDB Community Edition server, close the terminal or press kbd:[Ctrl+C].

// end::stop[]
