= TypeDB Cloud

== Preliminaries

Connecting to TypeDB Cloud requires:

* A cluster deployed through https://cloud.typedb.com?team_action=/clusters/deploy[TypeDB Cloud]
* The `address` and `port` of the server - these can be found on the page for your cluster
* A valid `username` and `password` - you should have set the password for the `admin` user while setting up your cluster

== Connecting your client

[tabs]
====
Console::
+
--
Run Console in CLI:

include::../tools/console.adoc[tag=connect_console]
--

Studio::
+
--
Run Studio and follow instructions below:

include::../tools/studio.adoc[tag=connect_cloud_studio]
--
====

== Connecting your application

For programmatic access, use one of the TypeDB xref:{page-component-version}@drivers::overview.adoc[drivers] via the network API:

[tabs]
====
Rust::
+
--
[,rust,indent=0]
----
    let uri = format!("{}:{}", address, port);
include::{page-version}@drivers::partial$tutorials/rust/src/main.rs[tags=driver_new]
----

--

Python::
+
--
[,python,indent=0]
----
    uri = f"{address}:{port}"
include::{page-version}@drivers::partial$tutorials/python/sample.py[tags=driver_new]
----
--

Java::
+
--
[,java,indent=0]
----
        uri = String.format("%s:%s", address, port)
include::{page-version}@drivers::partial$tutorials/java/src/main/java/org/example2/Main.java[tags=driver_new]
----

--

Node.js::
+
--
NOTE: Coming soon.
--

C#::
+
--
NOTE: Coming soon.
--

C++::
+
--
NOTE: Coming soon.
--

C::
+
--
NOTE: Coming soon.
--

HTTP::
+
--
Send a sign in xref:{page-version}@drivers::http/api-reference.adoc[HTTP request]:

.curl
[,console]
----
curl --request POST \
  --url https://{address}:{http_port}/v1/signin \
  --json '{"username": "USERNAME", "password": "PASSWORD"}'
----

Note that the `{http_port}` is different from the regular TypeDB port mentioned above and is defaulted to `8000`.

A successful response will contain an authentication token:

include::{page-version}@drivers::http/api-reference.adoc[tags=token-example]

Put it in the authorization header of the future requests.
See xref:{page-version}@drivers::http/index.adoc#_authentication[HTTP endpoint authentication] for more information.
--
====
