= TypeDB HTTP API Reference
:page-toclevels: 2

== Authorization

[#_sign_in]
=== Sign in

Request an API token to authenticate against the rest of the API using user credentials.
This token must be used as `ACCESS_TOKEN` for other protected methods.

[cols="h,3a"]
|===
| Token required           | No
| Method                   | `POST`
| URL                      | `/v1/signin`
| Request body             | include::{page-version}@drivers:resources:partial$http-api/requests/signin.json.adoc[]
| Request headers          | None
|===

*Responses:*

.200: OK
[%collapsible]
====
include::{page-version}@drivers:resources:partial$http-api/responses/signin.json.adoc[]
====

.400: Bad Request
[%collapsible]
====
Possible causes:

* Incorrectly formatted request

Response format:

include::{page-version}@drivers:resources:partial$http-api/responses/error.json.adoc[]
====

.401: Unauthorized
[%collapsible]
====
Possible causes:

* Invalid credentials

Response format:

include::{page-version}@drivers:resources:partial$http-api/responses/error.json.adoc[]
====

*Example request:*

[tabs]
====
curl::
+
[source,console]
----
curl --request POST \
  --url http://0.0.0.0:8000/v1/signin \
  --json '{"username": "USERNAME", "password": "PASSWORD"}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/signin"
body = {
    "username": "USERNAME",
    "password": "PASSWORD"
}

response = requests.post(url, json=body)
----

Rust::
+
[source,rust]
----
use reqwest;
use serde::Serialize;

#[derive(Serialize)]
struct Signin {
    username: String,
    password: String,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let signin = Signin {
        username: "username".to_string(),
        password: "password".to_string(),
    };
    let client = reqwest::Client::new();
    let resp = client
        .post("http://0.0.0.0:8000/v1/signin")
        .json(&signin)
        .send().await;
    Ok(())
}
----
====

*Example response:*

// tag::token-example[]
[source]
----
{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc0NDYzNTI5NSwiaWF0IjoxNzQ0NjIwODk1fQ.WEhmBTAXI_qZUlAB7zw52LDGJhnqfNTXS63QDSZlqds"
}
----
// end::token-example[]

== Server information

=== Version

Get the server's distribution and version information.

[cols="h,3a"]
|===
| Token required           | No
| Method                   | `GET`
| URL                      | `/v1/version`
| Request body             | None
| Request headers          | None
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-version"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----
curl --request GET \
  --url http://0.0.0.0:8000/v1/version
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/version"

response = requests.get(url)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .get("http://0.0.0.0:8000/v1/version")
        .send().await;
    Ok(())
}
----
====

*Example response:*

[source]
----
{
    "distribution": "TypeDB",
    "version": "3.2.0"
}
----

== Databases

=== Get databases

Get all databases present on the server.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `GET`
| URL                      | `/v1/databases`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-databases,401"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request GET \
  --url http://0.0.0.0:8000/v1/databases \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/databases"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.get(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .get("http://0.0.0.0:8000/v1/databases")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

=== Get database

Get a single database present on the server by name.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `GET`
| URL                      | `/v1/databases/DATABASE_NAME`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-database,401,404"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request GET \
  --url http://0.0.0.0:8000/v1/databases/DATABASE_NAME \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/databases/DATABASE_NAME"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.get(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .get("http://0.0.0.0:8000/v1/databases/DATABASE_NAME")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

=== Create database

Create a database on the server.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `POST`
| URL                      | `/v1/databases/DATABASE_NAME`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-empty,400,401"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request POST \
  --url http://0.0.0.0:8000/v1/databases/DATABASE_NAME \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/databases/DATABASE_NAME"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.post(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .post("http://0.0.0.0:8000/v1/databases/DATABASE_NAME")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

=== Delete database

Delete a database from the server by name.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `DELETE`
| URL                      | `/v1/databases/DATABASE_NAME`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-empty,400,401,404"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request DELETE \
  --url http://0.0.0.0:8000/v1/databases/DATABASE_NAME \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/databases/DATABASE_NAME"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.delete(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .delete("http://0.0.0.0:8000/v1/databases/DATABASE_NAME")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

=== Get database's schema

Retrieve a full schema text as a valid TypeQL define query string. This includes function definitions.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `GET`
| URL                      | `/v1/databases/DATABASE_NAME/schema`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-database-schema,400,401,404"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request GET \
  --url http://0.0.0.0:8000/v1/databases/DATABASE_NAME/schema \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/databases/DATABASE_NAME/schema"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.get(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .get("http://0.0.0.0:8000/v1/databases/DATABASE_NAME/schema")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

=== Get database's type schema

Retrieve the types in the schema as a valid TypeQL define query string.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `GET`
| URL                      | `/v1/databases/DATABASE_NAME/type-schema`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-database-schema,400,401,404"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request GET \
  --url http://0.0.0.0:8000/v1/databases/DATABASE_NAME/type-schema \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/databases/DATABASE_NAME/type-schema"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.get(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .get("http://0.0.0.0:8000/v1/databases/DATABASE_NAME/type-schema")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

== Users

=== Get users

Get all users present on the server.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `GET`
| URL                      | `/v1/users`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-users,401,403"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request GET \
  --url http://0.0.0.0:8000/v1/users \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/users"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.get(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .get("http://0.0.0.0:8000/v1/users")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

=== Get user

Get a single user present on the server by name.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `GET`
| URL                      | `/v1/users/USERNAME`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-user,401,403,404"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request GET \
  --url http://0.0.0.0:8000/v1/users/USERNAME \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/users/USERNAME"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.get(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .get("http://0.0.0.0:8000/v1/users/USERNAME")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

=== Create user

Create a new user on the server.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `POST`
| URL                      | `/v1/users/USERNAME`
| Request body             | include::{page-version}@drivers:resources:partial$http-api/requests/post-users.json.adoc[]
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-empty,400,401,403"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request POST \
  --url http://0.0.0.0:8000/v1/users/USERNAME \
  --header 'Authorization: Bearer {ACCESS-TOKEN}' \
  --json '{"password": "PASSWORD"}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/users/USERNAME"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}
body = {
    "password": "PASSWORD"
}

response = requests.post(url, headers=headers, json=body)
----

Rust::
+
[source,rust]
----
use reqwest;
use serde::Serialize;

#[derive(Serialize)]
struct UserCredentials {
    password: String,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let user_credentials = UserCredentials {
        password: "password".to_string(),
    };
    let client = reqwest::Client::new();
    let resp = client
        .post("http://0.0.0.0:8000/v1/users/USERNAME")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .json(&user_credentials)
        .send().await;
    Ok(())
}
----
====

=== Update user

Update credentials for a user present on the server.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `PUT`
| URL                      | `/v1/users/USERNAME`
| Request body             | include::{page-version}@drivers:resources:partial$http-api/requests/put-users.json.adoc[]
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-empty,400,401,403,404"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request PUT \
  --url http://0.0.0.0:8000/v1/users/USERNAME \
  --header 'Authorization: Bearer {ACCESS-TOKEN}' \
  --json '{"password": "PASSWORD"}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/users/USERNAME"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}
body = {
    "password": "PASSWORD"
}

response = requests.put(url, headers=headers, json=body)
----

Rust::
+
[source,rust]
----
use reqwest;
use serde::Serialize;

#[derive(Serialize)]
struct UserCredentials {
    password: String,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let user_credentials = UserCredentials {
        password: "password".to_string(),
    };
    let client = reqwest::Client::new();
    let resp = client
        .put("http://0.0.0.0:8000/v1/users/USERNAME")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .json(&user_credentials)
        .send().await;
    Ok(())
}
----
====

=== Delete user

Delete a user from the server by name.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `DELETE`
| URL                      | `/v1/users/USERNAME`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-empty,400,401,403,404"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request DELETE \
  --url http://0.0.0.0:8000/v1/users/USERNAME \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/users/USERNAME"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.delete(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .delete("http://0.0.0.0:8000/v1/users/USERNAME")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

== Transactions

=== Open transaction

Open a new transaction and receive a unique transaction id.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `POST`
| URL                      | `/v1/transactions/open`
| Request body             | include::{page-version}@drivers:resources:partial$http-api/requests/transactions-open.json.adoc[]
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

// tag::transaction-options[]
*Transaction options:*

[options="header"]
[cols="h,3a"]
|===
| Field | Description
| `transactionTimeoutMillis` |
include::{page-version}@manual:resources:partial$options-descriptions/transaction.adoc[tag=transaction-timeout]

Specified in milliseconds. **Default:**
include::{page-version}@manual:resources:partial$options-descriptions/transaction.adoc[tag=transaction-timeout-default]


| `schemaLockAcquireTimeoutMillis` |
include::{page-version}@manual:resources:partial$options-descriptions/transaction.adoc[tag=schema-lock-acquire-timeout]

Specified in milliseconds. **Default:**
include::{page-version}@manual:resources:partial$options-descriptions/transaction.adoc[tag=schema-lock-acquire-timeout-default]
|===
// end::transaction-options[]

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-transaction,400,404"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request POST \
  --url http://0.0.0.0:8000/v1/transactions/open \
  --header 'Authorization: Bearer {ACCESS-TOKEN}' \
  --json '{"databaseName": "DATABASE_NAME", "transactionType": "schema"}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/transactions/open"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}
body = {
    "databaseName": "DATABASE_NAME",
    "transactionType": "schema",
}

response = requests.post(url, headers=headers, json=body)
----

Rust::
+
[source,rust]
----
use reqwest;
use serde::Serialize;

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub enum TransactionType {
    Read,
    Write,
    Schema,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct Transaction {
    database_name: String,
    transaction_type: TransactionType,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let transaction = Transaction {
        database_name: DATABASE_NAME,
        transaction_type: TransactionType::Schema,
    };
    let client = reqwest::Client::new();
    let resp = client
        .post("http://0.0.0.0:8000/v1/transactions/open")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .json(&transaction)
        .send().await;
    Ok(())
}
----
====

=== Close transaction

Close a transaction without preserving its changes by transaction id.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `POST`
| URL                      | `/v1/transactions/TRANSACTION_ID/close`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-empty,400,403,404"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request POST \
  --url http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/close \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/close"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.post(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .post("http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/close")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

=== Commit transaction

Commit and close a transaction, preserving it changes on the server.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `POST`
| URL                      | `/v1/transactions/TRANSACTION_ID/commit`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-empty,400,403,404"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request POST \
  --url http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/commit \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/commit"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.post(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .post("http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/commit")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

=== Rollback transaction

Rolls back the uncommitted changes made via a transaction.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `POST`
| URL                      | `/v1/transactions/TRANSACTION_ID/rollback`
| Request body             | None
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-empty,400,403,404"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request POST \
  --url http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/rollback \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/rollback"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}

response = requests.post(url, headers=headers)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .post("http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/rollback")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .send().await;
    Ok(())
}
----
====

=== Query in transaction

Run a query within an open transaction.
This endpoint allows running multiple sequential queries before committing.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `POST`
| URL                      | `/v1/transactions/TRANSACTION_ID/query`
| Request body             | include::{page-version}@drivers:resources:partial$http-api/requests/transactions-query.json.adoc[]
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

// tag::query-options[]
*Query options:*

[options="header"]
[cols="h,3a"]
|===
| Field | Description
| `includeInstanceTypes` |
include::{page-version}@manual:resources:partial$options-descriptions/query.adoc[tag=include-instance-types]

**Default:**
include::{page-version}@manual:resources:partial$options-descriptions/query.adoc[tag=include-instance-types-default]


| `answerCountLimit` |
include::{page-version}@manual:resources:partial$options-descriptions/query.adoc[tag=answer-count-limit]
If there are more answers cut, a relevant `warning` will be provided in the response.

**Default:**
include::{page-version}@manual:resources:partial$options-descriptions/query.adoc[tag=answer-count-limit-default]

|===
// end::query-options[]

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-query,400,403,404,408"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request POST \
  --url http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/query \
  --header 'Authorization: Bearer {ACCESS-TOKEN}' \
  --json '{"query": "define entity person;"}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/query"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}
body = {
    "query": "define entity person;"
}

response = requests.post(url, headers=headers, json=body)
----

Rust::
+
[source,rust]
----
use reqwest;
use serde::Serialize;

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct Query {
    query: String,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let query = Query {
        query: "define entity person;".to_string(),
    };
    let client = reqwest::Client::new();
    let resp = client
        .post("http://0.0.0.0:8000/v1/transactions/TRANSACTION_ID/query")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .json(&query)
        .send().await;
    Ok(())
}
----
====

*Example responses for each concept:*

.Concept rows
[%collapsible]
====
.Request body
[%collapsible]
=====
include::{page-version}@drivers:resources:partial$http-api/requests/transactions-query-concept-rows-example.json.adoc[]
=====

include::{page-version}@drivers:resources:partial$http-api/responses/query-concept-rows-example.json.adoc[]
====

.Concept documents
[%collapsible]
====
.Request body
[%collapsible]
=====
include::{page-version}@drivers:resources:partial$http-api/requests/transactions-query-concept-documents-example.json.adoc[]
=====

include::{page-version}@drivers:resources:partial$http-api/responses/query-concept-documents-example.json.adoc[]
====

== One-shot query

Run a one-shot query.
This endpoint executes a query within a temporary transaction that is opened and then either committed or closed exclusively for this query.

[cols="h,3a"]
|===
| Token required           | Yes
| Method                   | `POST`
| URL                      | `/v1/query`
| Request body             | include::{page-version}@drivers:resources:partial$http-api/requests/query.json.adoc[]
| Request headers          | `Authorization: Bearer ACCESS_TOKEN`
|===

include::{page-version}@drivers::http/api-reference.adoc[tags="transaction-options,query-options"]

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="200-query,400,403,404,408"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----

curl --request POST \
  --url http://0.0.0.0:8000/v1/query \
  --header 'Authorization: Bearer {ACCESS-TOKEN}' \
  --json '{"databaseName": "DATABASE_NAME", "transactionType": "schema", "query": "define entity person;"}'
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/v1/query"

headers = {
    "Authorization": "Bearer {ACCESS-TOKEN}"
}
body = {
    "databaseName": "DATABASE_NAME",
    "transactionType": "schema",
    "query": "define entity person;"
}

response = requests.post(url, headers=headers, json=body)
----

Rust::
+
[source,rust]
----
use reqwest;
use serde::Serialize;

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub enum TransactionType {
    Read,
    Write,
    Schema,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct OneshotQuery {
    database_name: String,
    transaction_type: TransactionType,
    query: String,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let query = OneshotQuery {
        database_name: DATABASE_NAME,
        transaction_type: TransactionType::Schema,
        query: "define entity person;".to_string(),
    };
    let client = reqwest::Client::new();
    let resp = client
        .post("http://0.0.0.0:8000/v1/query")
        .header(reqwest::header::AUTHORIZATION, "Bearer {ACCESS-TOKEN}")
        .json(&query)
        .send().await;
    Ok(())
}
----
====

*Example responses for each concept:*

[#_query_example_responses_rows]
.Concept rows
[%collapsible]
====
.Request body
[%collapsible]
=====
include::{page-version}@drivers:resources:partial$http-api/requests/query-concept-rows-example.json.adoc[]
=====

include::{page-version}@drivers:resources:partial$http-api/responses/query-concept-rows-example.json.adoc[]
====

[#_query_example_responses_documents]
.Concept documents
[%collapsible]
====
.Request body
[%collapsible]
=====
include::{page-version}@drivers:resources:partial$http-api/requests/query-concept-documents-example.json.adoc[]
=====

include::{page-version}@drivers:resources:partial$http-api/responses/query-concept-documents-example.json.adoc[]
====

== Health check

Check that the server is accessible and healthy.

[cols="h,3a"]
|===
| Token required           | No
| Method                   | `GET`
| URL                      | `/health`
| Request body             | None
| Request headers          | None
|===

*Responses:*

include::{page-version}@drivers:resources:partial$http-api/responses/details.adoc[tags="204-empty"]

*Example request:*

[tabs]
====
curl::
+
[source,console]
----
curl --request GET \
  --url http://0.0.0.0:8000/health
----

Python::
+
[source,python]
----
import requests

url = "http://0.0.0.0:8000/health"

response = requests.get(url)
----

Rust::
+
[source,rust]
----
use reqwest;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::new();
    let resp = client
        .get("http://0.0.0.0:8000/health")
        .send().await;
    Ok(())
}
----
====
