= Creating users

To create a new user, connect to TypeDB and follow the steps below:

[tabs]
====
Console::
+
--
Run the following command:

[,bash]
----
user create <username>
----
Where `<username>` is the name of the user.

You will be prompted for a password.
--

Studio::
+
[NOTE]
======
Coming soon.
======
====

To create a new user programmatically:

[tabs]
====
Rust::
+
--
[,rust]
----
let result = driver.users().create("<username>", "<password>").await;
----

Where `driver` is an instance of a driver, connected to TypeDB, `"<username>"` is the name of the user, and `"<password>"` is its password.
--

Python::
+
--
[,python]
----
driver.users.create("<username>", "<password>")
----

Where `driver` is an instance of a driver, connected to TypeDB, `"<username>"` is the name of the user, and `"<password>"` is its password.
--

Java::
+
--
[,java]
----
driver.users().create("<username>", "<password>");
----

Where `driver` is an instance of a driver, connected to TypeDB, `"<username>"` is the name of the user, and `"<password>"` is its password.
--

Node.js::
C#::
C++::
C::
+
[NOTE]
======
Coming soon.
======

HTTP::
+
--
Send a users POST xref:{page-version}@drivers::http/api-reference.adoc[HTTP request]:

.curl
[,console]
----
curl --request POST \
  --url {http/https}://{address}:{http_port}/v1/users/<username> \
  --header 'Authorization: Bearer {ACCESS-TOKEN}' \
  --json '{"password": "<password>"}'
----
Where `{ACCESS_TOKEN}` is your xref:{page-version}@drivers::http/index.adoc#_authentication[authentication token], `<username>` is the name of the user, and `"<password>"` is its password.
--
====
