= Updating passwords

To update a user's password, connect to TypeDB and follow the steps below:

[tabs]
====
Console::
+
--
Run the following command:

[,bash]
----
user password-update <username>
----
Where `<username>` is the name of the user.

You will be prompted for a new password.
--

Studio::
+
--
[NOTE]
======
Coming soon.
======
--
====

To update a user's password programmatically:

[tabs]
====
Rust::
+
--
[,rust]
----
let user = driver.users().get("<username>").await?;
let result = user.update_password("<password>").await;
----

Where `driver` is an instance of a driver, connected to TypeDB, `"<username>"` is the name of the user, and `"<password>"` is its new password.
--

Python::
+
--
[,python]
----
driver.users.get("<username>").update_password("<password>")
----

Where `driver` is an instance of a driver, connected to TypeDB, `"<username>"` is the name of the user, and `"<password>"` is its new password.
--

Java::
+
--
[,java]
----
driver.users().get("<username>").updatePassword("<password>");
----

Where `driver` is an instance of a driver, connected to TypeDB, `"<username>"` is the name of the user, and `"<password>"` is its new password.
--

Node.js::
C#::
C++::
C::
+
[NOTE]
======
Coming soon.
======

HTTP::
+
--
Send a users PUT xref:{page-version}@drivers::http/api-reference.adoc[HTTP request]:

.curl
[,console]
----
curl --request PUT \
  --url {http/https}://{address}:{http_port}/v1/users/<username> \
  --header 'Authorization: Bearer {ACCESS-TOKEN}' \
  --json '{"password": "<password>"}'
----
Where `{ACCESS_TOKEN}` is your xref:{page-version}@drivers::http/index.adoc#_authentication[authentication token], `<username>` is the name of the user, and `"<password>"` is its new password.
--
====
