= Deleting databases

== From clients

To delete a database, connect to TypeDB and follow the steps below:

[tabs]
====
Console::
+
--
Run the following command:

[,bash]
----
database delete social_network
----

Where `social_network` is the name of the database.
--

Studio::
+
[NOTE]
======
Coming soon.
======
====

== From drivers

To delete a database programmatically:

[tabs]
====
Rust::
+
--
[,rust]
----
let database = driver.databases().get("social_network").await?;
let result = database.delete().await;
----

Where `driver` is an instance of a driver, connected to TypeDB, and `"social_network"` is the name of the database.
--

Python::
+
--
[,python]
----
driver.databases.get("social_network").delete()
----

Where `driver` is an instance of a driver, connected to TypeDB, and `"social_network"` is the name of the database.
--

Java::
+
--
[,java]
----
driver.databases().get("social_network").delete();
----

Where `driver` is an instance of a driver, connected to TypeDB, and `"social_network"` is the name of the database.
--

Node.js::
C#::
C++::
C::
+
[NOTE]
======
Coming soon.
======

HTTP::
+
--
Send a databases DELETE xref:{page-version}@drivers::http/api-reference.adoc[HTTP request]:

.curl
[,console]
----
curl --request DELETE \
  --url {http/https}://{address}:{http_port}/v1/databases/social_network \
  --header 'Authorization: Bearer {ACCESS-TOKEN}'
----
Where `{ACCESS_TOKEN}` is your xref:{page-version}@drivers::http/index.adoc#_authentication[authentication token] and `social_network` is the name of the database.
--
====
