= TypeDB 2.x to TypeDB 3.x: what's changed

This page outlines the key updates of TypeDB 3.x compared to 2.x you should be aware of while transitioning between these versions.

[NOTE]
====
This section highlights **changes from TypeDB 2.x**, not all new features in 3.x.
Explore the xref:{page-version}@manual::index.adoc[Manual], xref:{page-version}@typeql::index.adoc[TypeQL Documentation], and https://github.com/typedb/typedb/releases[release notes] for the full picture.
Stay tuned for upcoming blogs showcasing new features!
====

Click on a feature below for detailed documentation and examples.

== TypeDB and TypeQL

* **Sessions Removed:** Connections to TypeDB now only require opening a `schema`, `write`, or `read` xref:{page-version}@manual::queries/transactions.adoc[transaction].
* **Integer Value Type Renamed:** `long` is now xref:{page-version}@typeql::values/integer.adoc[`integer`].
* **Kinds Introduced:** no more predefined root types and their subtyping through `person sub entity`, `friendship sub relation`, or `name sub attribute`.
Each new type should be declared with an explicit kind: `entity person`, `relation friendship`, and `attribute name`.
Check out xref:{page-version}@manual::schema/schema_structure.adoc[] for more.
* **Expanded User Management:** Authorization and user management are now included in all TypeDB editions.
Default credentials, if applicable, can be found in the xref:{page-version}@manual::connect/index.adoc[Connection Manual].
* **Updated Query Syntax:**
- xref:{page-version}@typeql::schema/undefine.adoc[`undefine`] and xref:{page-version}@typeql::pipelines/delete.adoc[`delete`] now explicitly "point" to their removed targets, reducing ambiguity.
- xref:{page-version}@typeql::pipelines/fetch.adoc[`fetch`] syntax aligns with JSON output formatting.
- xref:{page-version}@typeql::pipelines/match.adoc[`match`] produces visible row-like results itself (similarly to xref:{page-version}@typeql::pipelines/insert.adoc[`insert`], etc): no more `get` s!
- All `$vars` start with `$`: no more `?` for value variables!
However, it is still easy to differentiate their declaration with the new xref:{page-version}@typeql::statements/let-eq.adoc[`let` keyword].
Check out some read queries examples xref:{page-version}@manual::CRUD/reading.adoc[here].
* **Annotations and Statements Consolidated:** xref:{page-version}@typeql::annotations/abstract.adoc[`abstract`] and xref:{page-version}@typeql::annotations/regex.adoc[`regex`] are now grouped under xref:{page-version}@typeql::annotations/index.adoc[@annotations].
[#_specialize]
* **Smoother trait specialization:**
- It is possible to redefine already inherited `owns` and `plays` on subtypes, adding more annotations to them.
- As before, use the `as` keyword to xref:{page-version}@typeql::statements/relates.adoc[specialize a `relates`].
* **Default Cardinalities:**
- Default cardinalities are applied to `owns`, `relates`, and `plays` if not explicitly defined.
- Default `plays` cardinality: `@card(0..)` (unlimited).
- Default `owns` and `relates` cardinality: `@card(0..1)` (up to one instance).
Explicitly define cardinalities for traits expecting multiple instances to avoid data corruption and optimize database performance.
* **Rules and Inference Replaced:** Rules are now replaced by xref:{page-version}@typeql::functions/index.adoc[functions], requiring explicit functions execution instead of inference, but offering more abstraction and flexibility.

[#_major_changes_drivers]
== TypeDB Drivers

**API Simplification** for smoother UX and better maintenance.
Visit the xref:{page-version}@drivers::index.adoc[Drivers manual] to access their full documentation.

- Now, all schema and data fetching and modifications are performed through a single `transaction.query("your query")` interface.
- No more `query().insert()` and `query().define()`.
- No more `concept.delete()` or `concept.getHas()`.
- Concept structure is preserved (the only difference: `Thing` is renamed to `Instance`), casts are available, and it is possible to retrieve something simple as a type's label or an attribute's value, that are sent with the type itself.
- In OOP languages (like Java and Python), concepts have `try` versions of their methods, available for any concept and returning optional results.
Using casting, the concrete methods returning results directly become available, as in 2.x.

[#_temporarily_missing]
== Temporarily missing features

This section contains the list of features that were introduced in 2.x, but are still under development in 3.x. **Coming soon!**
Take into account that some of your processes can be blocked if you previously relied on these features.

=== TypeDB and TypeQL

* Instantiation restriction for inherited `owns` and `plays` (used to `as`).
An enhanced approach is in development (NOTE: you don't need the `as` keyword to <<#_specialize, specialize>> an ownership of an inherited super attribute type with an ownership of its subtype, but you cannot "hide" the original definition from inheritance).
* Scaling support for Cloud and Enterprise editions.

=== TypeDB Drivers

* Node.js, C, C++, and C# drivers are not yet available.
Consider using one of xref:{page-version}@drivers::index.adoc[the available languages] or xref:{page-version}@drivers::http/index.adoc[the HTTP Endpoint].

[#_having_troubles]
== Having troubles?

For troubleshooting tips and guidance, refer to the xref:{page-version}@manual::troubleshooting/index.adoc[Troubleshooting Manual].
