= TypeDB 2.x to TypeDB 3.x: migration process

This page gives recommendations for server and driver upgrades between the two major versions of TypeDB, as well as a step-by-step example of such a migration.

== Migration plan

1. **Understand the scope of changes** by referring to the xref:{page-version}@manual::migration/2_to_3/diff.adoc[major changes] page.
1. **Review the xref:{page-version}@manual::migration/2_to_3/diff.adoc#_temporarily_missing[missing features] list** before starting your migration.
Some features might not yet be available in 3.x, and you may need to wait for a newer version to proceed.
1. *(Optional)* Refresh your knowledge and adjust to the new versions of TypeDB and TypeQL by following the updated xref:{page-version}@home::quickstart.adoc[Quickstart Guide].
1. **Set up TypeDB 3.x** by following the xref:{page-version}@manual::configure/index.adoc[Configuration Manual].
1. **Migrate your TypeDB 2.x database** following the xref:#_step_by_step[step-by-step instructions below].
The setup process remains largely unchanged from 2.x.
1. *(Optional)* Update your supporting queries using the xref:{page-version}@manual::schema/index.adoc[Schema] and xref:{page-version}@manual::CRUD/index.adoc[CRUD] manuals.
1. *(Optional)* Update your drivers.
Consult the xref:{page-version}@drivers::index.adoc[Drivers Manual] and the xref:{page-version}@manual::migration/2_to_3/diff.adoc#_major_changes_drivers[major driver changes] list for details.

[#_step_by_step]
== Step-by-step example

This section showcases a step-by-step example of migrating a database between TypeDB 2.x and TypeDB 3.x using xref:{page-version}@manual::maintenance/export_import.adoc[major changes][export and import].

This example uses a database called `social-network`.
It contains an arbitrary set of data and the 2.x schema provided below.

[#_schema_reference]
.social-network's 2.x schema
[%collapsible]
====
.social-network.typeql
[,typeql]
----
include::{page-version}@manual:resources:partial$migration/2_to_3/schema-2x.tql[tag=full-query]
----
====

[#_prepare_data]
=== Optional: resolve data conflicts

While most of the changes in TypeDB 3.x affect only the schema, there is also one very important change in data, which can lead to errors on the <<_import, import stage>> of this guide.

**Attributes can no longer own attributes** in TypeDB 3.x.
If your data contains attributes owning attributes, you will see an error like:

[source]
----
Invalid migration item received: attributes cannot own attributes in this version of TypeDB (deprecated).
----

In this situation, an additional step is required before proceeding, and it will require modifications of the original 2.x's database.

==== Move attributed owned by attributes

This is an example of migration of attributes owned by attributes for the <<_schema_reference, referenced schema>>.

Our goal is to move `bio-version` from `bio` to `page` owning the `bio` attributes.
This way, both `bio` and `bio-version` will be attached to the same entity (note that it's only one of the ways to redesign this schema).

First, using a schema write transaction, define the additional required trait of `page`:

[,typeql]
----
include::{page-version}@manual:resources:partial$migration/2_to_3/attribute-migration-queries.tql[tag=step1-define-entity-ownership]
----

Then, using a data write transaction, perform the data moving between `bio`s and `page`s:

[,typeql]
----
include::{page-version}@manual:resources:partial$migration/2_to_3/attribute-migration-queries.tql[tag=step2-move-data]
----

Finally, verify that the data is moved correctly.
As an additional step of verification, you can try undefining the original ownership to verify that it's now redundant:

[,typeql]
----
include::{page-version}@manual:resources:partial$migration/2_to_3/attribute-migration-queries.tql[tag=step3-undefine-attribute-ownership]
----

Now your data is ready to get migrated to TypeDB 3.x!

[#_export]
=== Export the database from TypeDB 2.x

Use xref:2.x@manual::configuring/export.adoc#_export[2.x export] to export your TypeDB 2.x database as a schema definition file and a data file.

While your server is running, execute `typedb server export` using the same server binary:

[source,console]
----
typedb server export --database=social-network --port=1729 --schema=social-network.typeql --data=social-network.typedb
----

[#_prepare_schema]
=== Prepare the new schema

**Manually update your schema definition file.**

- The xref:{page-version}@manual::migration/2_to_3/diff.adoc[major changes] page highlights the most common updates needed.
- For simplicity, rules can be completely removed.
Additional queries can be run to define functions as their replacements later.

This step can require a couple of iterations until you reach the final state of your new schema you will be satisfied with.
Use error messages during application to guide adjustments.

This is a sample example of the updated ``social-network``'s schema, written in TypeQL 3.x:

.social-network's 3.x schema
[%collapsible]
====
.social-network-3x.typeql
[,typeql]
----
include::{page-version}@manual:resources:partial$migration/2_to_3/schema-3x.tql[tag=full-query]
----

Noticeable highlights:

- Attribute types can be subtyped even if they are not abstract.
- Attributes can no longer own attributes.
See `bio-version` for an example of such redesign.
- `long` is now `integer`.
- We can restrict cardinalities of `relates`, `owns`, and `plays` using the `@card` annotation.
Default cardinality values protect your data, but they may not suite your needs. Consider overriding them explicitly.
- We can redeclare traits like `owns` on subtypes to put additional constraints on them.
- While there are no `as` keyword for `owns` and `plays`, in most cases, like ours, it's not needed.
E.g., the previously overridden `owns id` does not require overriding in 3.x as it's an ownership of an abstract attribute, so it cannot be instantiated without type specialization (e.g., `owns post-id`).
- More constraints can be moved from your application logic to the schema: see the implication of `@values`, an enum-like constraint of TypeQL.

If you want to put data constraints, but your data does not yet satisfy them, you can start with a relaxed schema and then add the constraints required via additional `define` queries.
====

[#_import]
=== Import the database into TypeDB 3.x

Launch a xref:{page-version}@manual::install/index.adoc[TypeDB 3.x server] and connect to it using a compatible xref:{page-version}@manual::tools/console.adoc[TypeDB Console].

In TypeDB Console, execute a `database import` command:

[source,console]
----
database import social-network /path-to-updated-schema/social-network-3x.typeql /path-to-2.x-export/social-network.typedb
----

[NOTE]
====
You can operate other server's databases without restrictions while the new database is being imported.
====

In case of successful migration, you will see:

[source]
----
Successfully imported database.
----

Otherwise, a descriptive error will be shown.
After fixing this error, retry the same command.

[#_after_import]
=== After import

From this point, your database is completely functional.
Its schema and data are synchronized and technically correct.

We recommend running a few read queries to verify that the migration was logically successful and familiarize yourself with the updated TypeQL and your new schema.

If necessary, define TypeQL functions and update any queries that previously relied on the removed rules to use the new functions instead.

Visit xref:{page-version}@manual::migration/2_to_3/diff.adoc[] and xref:{page-version}@manual::index.adoc[] to learn more about TypeDB 3.x.
Enjoy your journey!

[#_having_troubles]
== Having troubles?

For troubleshooting tips and guidance, refer to the xref:{page-version}@manual::troubleshooting/index.adoc[Troubleshooting Manual].
