= TypeDB Studio

[.float-group]
--
TypeDB Studio is an interactive visual environment for managing and querying TypeDB databases.

With Studio, developers can efficiently manage databases, execute queries, and explore query results,
all within a unified environment.
--

[cols-2]
--
.https://studio.typedb.com[Open TypeDB Studio]
[.clickable]
****
Launch TypeDB Studio directly from your web browser.
****

.link:https://github.com/typedb/typedb-studio/[GitHub,window=_blank]
[.clickable]
****
Browse the source code of TypeDB Studio.
****
--

[NOTE]
====
For installation instructions, see xref:{page-version}@new_home::install/studio-console.adoc[Studio & Console Installation].
====

== Quickstart

=== Connect to TypeDB

Select TypeDB edition below, and follow the instructions:

include::{page-version}@new_home::partial$studio_connect.adoc[tag=connect_studio]

=== Select a database

To select a database to work with, use the dropdown menu on the right of the database icon in the top toolbar. You can also create new databases here.

TypeDB Studio will automatically select a *default* database if there are no others present.

== Querying

You can run queries against the connected TypeDB server using TypeDB Studio's https://studio.typedb.com/query[query tool].

=== Write a query

You can write TypeQL queries in the Query pane.

The Query pane contains a code editor that offers TypeQL highlighting and simple autocompletion.

=== Run a query

When your query is ready to run, hit "Run query" in the Query pane.

Results are printed to the Run pane.

=== Query results

The Run pane offers three different views of results - you can choose between *Log*, *Table* and *Raw*.

The Log contains textual output, similar to TypeDB Console, as well as input log, and error messages.

Table view is well suited for visualising the answers of *match* and *fetch* queries in a tabular format, where each row represents an answer, and each column represents a variable.

Raw output allows you to see the raw HTTP response from TypeDB.

=== Schema pane

The Schema pane lists your schema objects and their capabilities - e.g. owned attributes and played roles.

It acts as a reference panel indicating what you can query.

=== History pane

All queries and transaction operations are timestamped and logged to the History pane. Any errors that occur can be retrieved from this pane.

=== Transaction controls

By default, transactions are fully managed by TypeDB Studio. A transaction opens when you start running a query, and commits when a schema/write query is done or closes when a read query is done.

For more fine-grained control, you can use the top bar to change the transaction mode from *auto* to *manual*. This allows you to open transactions, and perform multiple queries within a transaction before closing or committing.

Only one transaction can be open concurrently within a single instance of TypeDB Studio.

=== Connection management

To connect, disconnect, or change connection settings, use the connection button in the top bar.
While connected to TypeDB, the button changes its label to the server's address or the custom name provided when setting up the connection.

=== Error handling

Query-level errors are printed to Log Output. These are typically errors returned directly from TypeDB, and will contain detailed error codes and explanations of the problem (e.g: illegal TypeQL semantics)

Transaction-level errors will trigger an error popup notification.

Both types of errors can be viewed and copied to the clipboard by visiting the History pane on the Query page. 