config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]

build:
  correctness:
    deploy-3.x-development:
      filter:
        owner: typedb
        branch: 3.x-development
      image: vaticle-ubuntu-21.04
      type: foreground
      command: |
        export RELEASE_DOCS_USERNAME=$REPO_GITHUB_USERNAME
        export RELEASE_DOCS_EMAIL=$REPO_GITHUB_EMAIL
        export RELEASE_DOCS_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @typedb_dependencies//tool/release:docs -- $FACTORY_OWNER typedb-docs-web development $FACTORY_REPO content/3.x $FACTORY_COMMIT
    deploy-3.x-production:
      filter:
        owner: typedb
        branch: 3.x-master
      image: vaticle-ubuntu-21.04
      type: foreground
      command: |
        export RELEASE_DOCS_USERNAME=$REPO_GITHUB_USERNAME
        export RELEASE_DOCS_EMAIL=$REPO_GITHUB_EMAIL
        export RELEASE_DOCS_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @typedb_dependencies//tool/release:docs -- $FACTORY_OWNER typedb-docs-web master $FACTORY_REPO content/3.x $FACTORY_COMMIT
  execution:
    - deploy-development
    - deploy-production
