= TypeDB Enterprise

This page is an installation guide for TypeDB Enterprise, a self-hosted deployment of TypeDB.

TypeDB Enterprise is distributed and installed separately from other editions of TypeDB and requires a license.
You can get a license for it from our sales team: contact us via
mailto:cloud@typedb.com[e-mail,window=_blank] or
https://typedb.com/deploy?dialog=contact[contact form,window=_blank].

[IMPORTANT]
====
TypeDB is also available as a fully managed cloud service with no installation required at
https://cloud.typedb.com/[cloud.typedb.com,window=_blank].
====

== System Requirements

TypeDB Enterprise runs on macOS, Linux, and Windows.

== Download and Install

Install your TypeDB Enterprise distribution with <<_using_docker,Docker>> or via manual
<<_manual_download_and_installation,download and installation>>.

You can deploy a cluster of TypeDB Enterprise servers
<<_deploying_manually,manually>> or via <<_deploying_with_kubernetes,Kubernetes>>.

If you need a license, contact our mailto:cloud@typedb.com[sales team].

[#_using_docker]
=== Docker

include::{page-version}@new_home::partial$enterprise_docker.adoc[tag=docker]

[#_manual_download_and_installation]
=== Manual installation

include::{page-version}@new_home::partial$enterprise_manual.adoc[tag=manual]

== Connecting

To check whether TypeDB Enterprise is working and interact with it, connect with 
xref:{page-version}@new_tools::studio.adoc[TypeDB Studio] or xref:{page-version}@new_tools::console.adoc[TypeDB Console].
Note that xref:{page-version}@new_tools::console.adoc[TypeDB Console] is also available from your TypeDB Enterprise directory:

[source,bash]
----
./typedb console --cloud 127.0.0.1:1729 --username admin --password
----

To run TypeDB Console from a Docker container, run:

[source,bash]
----
docker exec -ti typedb-cloud bash -c '/opt/typedb-cloud-all-linux-x86_64/typedb console --cloud 127.0.0.1:1729 --username admin --password'
----

[#_deploying_manually]
== Deploying manually

include::{page-version}@new_home::partial$enterprise_cluster.adoc[tag=cluster]

[#_deploying_with_kubernetes]
== Deploying with Kubernetes

To deploy a TypeDB Enterprise cluster with Kubernetes, we can use the https://helm.sh/[Helm] package manager.

include::{page-version}@new_home::partial$enterprise_kubernetes.adoc[leveloffset=+1] 